project_id = "zeiqetimpspjgppfhbdu"

[functions.get-maps-config]
verify_jwt = false

[functions.pesapal-auth]
verify_jwt = false

[functions.pesapal-register-ipn]
verify_jwt = false

[functions.pesapal-create-order]
verify_jwt = true

[functions.create-pesapal-order]
verify_jwt = false

[functions.cleanup-expired-carts]
verify_jwt = false

[functions.pesapal-ipn]
verify_jwt = false

[functions.pesapal-status]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.asili-chat]
verify_jwt = false