-- Insert experiences from mock data for admin user
-- First, let's get the admin's partner profile id
-- ed72b0f5-4fec-48e3-b6fa-977a00420baa

INSERT INTO public.experiences (
  id, partner_id, title, slug, description, hero_image, gallery, 
  themes, activities, price_kes_adult, child_half_price_rule, 
  capacity, visible_on_marketplace, location_text, created_at, updated_at
) VALUES
-- Koija Cultural Village
(gen_random_uuid(), 'ed72b0f5-4fec-48e3-b6fa-977a00420baa', 'Koija Cultural Village', 'koija-cultural-village', 'Immerse yourself in the rich cultural heritage of the Samburu people at Koija Cultural Village. Experience traditional dances, learn about ancient customs, and witness the daily life of this proud community. This authentic cultural exchange supports local livelihoods while preserving important traditions for future generations.', '/lovable-uploads/08763604-1a22-4da5-a8a1-4daf65cb4b32.png', '["https://zeiqetimpspjgppfhbdu.supabase.co/storage/v1/object/public/partner-images/08763604-1a22-4da5-a8a1-4daf65cb4b32.png", "https://zeiqetimpspjgppfhbdu.supabase.co/storage/v1/object/public/partner-images/3a4d487a-fe3a-40ce-aa28-18adf4191e69.png"]', '["Community & cultural exploration"]', '["village", "culture", "community"]', 2000, false, 15, true, 'Samburu County, Kenya', now(), now()),

-- Sera On-Foot Rhino Tracking
(gen_random_uuid(), 'ed72b0f5-4fec-48e3-b6fa-977a00420baa', 'Sera On-Foot Rhino Tracking', 'sera-on-foot-rhino-tracking', 'Experience the thrill of tracking endangered black rhinos on foot in the Sera Conservancy. This unique conservation experience offers intimate wildlife encounters while supporting critical anti-poaching efforts and community-based conservation initiatives in Samburu.', '/lovable-uploads/73526904-0f02-4d36-9590-456e0dd5628a.png', '["https://zeiqetimpspjgppfhbdu.supabase.co/storage/v1/object/public/partner-images/73526904-0f02-4d36-9590-456e0dd5628a.png", "https://zeiqetimpspjgppfhbdu.supabase.co/storage/v1/object/public/partner-images/dc2fa3f6-3095-4f03-9f50-d78d7cceba81.png"]', '["Wildlife conservation"]', '["rhino", "tracking", "walking"]', 4000, false, 10, true, 'Sera Conservancy, Samburu', now(), now()),

-- Giraffe at Ruko Sanctuary
(gen_random_uuid(), 'ed72b0f5-4fec-48e3-b6fa-977a00420baa', 'Giraffe at Ruko Sanctuary', 'giraffe-at-ruko-sanctuary', 'Get up close with endangered Rothschild''s giraffes at Ruko Community Conservancy. Learn about giraffe conservation efforts, feeding behaviors, and the community''s role in protecting these magnificent creatures in their natural habitat.', '/lovable-uploads/21799448-fabe-49a5-b8b2-3fd811cc804c.png', '["https://zeiqetimpspjgppfhbdu.supabase.co/storage/v1/object/public/partner-images/21799448-fabe-49a5-b8b2-3fd811cc804c.png", "https://zeiqetimpspjgppfhbdu.supabase.co/storage/v1/object/public/partner-images/235266ed-14bb-4381-9304-a9f8e2934776.png"]', '["Wildlife conservation"]', '["giraffe", "sanctuary"]', 2000, false, 15, true, 'Ruko Conservancy, Samburu', now(), now()),

-- Colobus Conservation Guided Eco Tours
(gen_random_uuid(), 'ed72b0f5-4fec-48e3-b6fa-977a00420baa', 'Colobus Conservation Guided Eco Tours', 'colobus-conservation-guided-eco-tours', 'Discover the fascinating world of Colobus monkeys and other primates along Kenya''s coast. This guided eco-tour showcases conservation efforts to protect endangered primates while supporting local communities through sustainable tourism.', '/lovable-uploads/1cbd1d3d-c30b-45be-a09e-8c9cc6f1f87b.png', '["https://zeiqetimpspjgppfhbdu.supabase.co/storage/v1/object/public/partner-images/1cbd1d3d-c30b-45be-a09e-8c9cc6f1f87b.png", "https://zeiqetimpspjgppfhbdu.supabase.co/storage/v1/object/public/partner-images/1cbd3f9c-ed73-43d0-97e2-61830c34802f.png"]', '["Wildlife conservation"]', '["primates", "eco-tour"]', 1500, false, 12, true, 'Coastal Kenya', now(), now()),

-- Ocean Conservation Day – Watamu
(gen_random_uuid(), 'ed72b0f5-4fec-48e3-b6fa-977a00420baa', 'Ocean Conservation Day – Watamu', 'ocean-conservation-day-watamu', 'Join a hands-on ocean conservation workshop in Watamu. Learn about marine ecosystems, participate in beach cleanups, and discover how local communities are protecting coral reefs and marine life along Kenya''s coast.', '/lovable-uploads/a6c0b2b9-fd77-4472-a600-d2f163add078.png', '["https://zeiqetimpspjgppfhbdu.supabase.co/storage/v1/object/public/partner-images/a6c0b2b9-fd77-4472-a600-d2f163add078.png", "https://zeiqetimpspjgppfhbdu.supabase.co/storage/v1/object/public/partner-images/145c30f9-65a9-4b28-87ad-97dac17376b7.png"]', '["Conservation education"]', '["ocean", "workshop"]', 1000, false, 20, true, 'Watamu, Coastal Kenya', now(), now()),

-- Tree Walk – Kenya Forest Heritage
(gen_random_uuid(), 'ed72b0f5-4fec-48e3-b6fa-977a00420baa', 'Tree Walk – Kenya Forest Heritage', 'tree-walk-kenya-forest-heritage', 'Explore Kenya''s indigenous forest heritage through guided tree walks. Learn about native species, traditional uses of forest resources, and ongoing conservation efforts to preserve these vital ecosystems for future generations.', '/lovable-uploads/f0dcab56-c695-41ac-bf57-3a9e350158f0.png', '["https://zeiqetimpspjgppfhbdu.supabase.co/storage/v1/object/public/partner-images/f0dcab56-c695-41ac-bf57-3a9e350158f0.png", "https://zeiqetimpspjgppfhbdu.supabase.co/storage/v1/object/public/partner-images/7ecd7176-f5b7-48b1-ae30-b697e0501c03.png"]', '["Conservation education"]', '["forest", "walk", "trees"]', 500, false, 15, true, 'Nairobi and surroundings', now(), now()),

-- Dudu Walk – Insect Exploration
(gen_random_uuid(), 'ed72b0f5-4fec-48e3-b6fa-977a00420baa', 'Dudu Walk – Insect Exploration', 'dudu-walk-insect-exploration', 'Discover the incredible world of insects and their crucial role in ecosystems. This educational walk explores Kenya''s diverse insect life and teaches about their importance in conservation and sustainable living.', '/lovable-uploads/755bb09b-50ae-4b81-8ee4-ed16c5874e40.png', '["https://zeiqetimpspjgppfhbdu.supabase.co/storage/v1/object/public/partner-images/755bb09b-50ae-4b81-8ee4-ed16c5874e40.png", "https://zeiqetimpspjgppfhbdu.supabase.co/storage/v1/object/public/partner-images/b8fd9d98-7dde-4ace-93a4-7f45b5858549.png"]', '["Conservation education"]', '["insects", "education"]', 500, false, 15, true, 'Nairobi', now(), now()),

-- Nairobi Giraffe Centre (AFEW)
(gen_random_uuid(), 'ed72b0f5-4fec-48e3-b6fa-977a00420baa', 'Nairobi Giraffe Centre (AFEW)', 'nairobi-giraffe-centre-afew', 'Visit the famous Giraffe Centre and get up close with endangered Rothschild''s giraffes. Learn about conservation efforts, feed the giraffes, and support AFEW''s mission to protect Kenya''s wildlife through education and conservation programs.', '/lovable-uploads/68c0cf79-0a97-4ec1-82b4-1f5f443b3d20.png', '["https://zeiqetimpspjgppfhbdu.supabase.co/storage/v1/object/public/partner-images/68c0cf79-0a97-4ec1-82b4-1f5f443b3d20.png", "https://zeiqetimpspjgppfhbdu.supabase.co/storage/v1/object/public/partner-images/2998745d-d343-4471-b0b6-6a66d49fce09.png"]', '["Wildlife conservation"]', '["giraffe", "education"]', 1500, true, 20, true, 'Nairobi', now(), now()),

-- Reteti Community Elephant Experience
(gen_random_uuid(), 'ed72b0f5-4fec-48e3-b6fa-977a00420baa', 'Reteti Community Elephant Experience', 'reteti-community-elephant-experience', 'Experience the heartwarming work of Reteti Elephant Sanctuary, Kenya''s first community-owned elephant sanctuary. Meet orphaned elephants, learn about their rescue and rehabilitation, and discover how local communities are leading conservation efforts.', '/lovable-uploads/d42dcb33-a2f6-4418-8d2a-921127f8d45a.png', '["https://zeiqetimpspjgppfhbdu.supabase.co/storage/v1/object/public/partner-images/d42dcb33-a2f6-4418-8d2a-921127f8d45a.png", "https://zeiqetimpspjgppfhbdu.supabase.co/storage/v1/object/public/partner-images/12a93a46-de0f-4be8-a867-015fd5d9daa3.png"]', '["Wildlife conservation"]', '["elephant", "sanctuary"]', 400, false, 10, true, 'Northern Kenya', now(), now()),

-- Ol Pejeta – Bush Bird Walks
(gen_random_uuid(), 'ed72b0f5-4fec-48e3-b6fa-977a00420baa', 'Ol Pejeta – Bush Bird Walks', 'ol-pejeta-bush-bird-walks', 'Explore the diverse birdlife of Ol Pejeta Conservancy on guided bush walks. Spot endemic species, learn about bird behavior and habitats, and discover how conservation efforts protect avian biodiversity in this renowned wildlife sanctuary.', '/lovable-uploads/4fcd9e54-4c77-4a54-88fe-56c8ddc0b495.png', '["https://zeiqetimpspjgppfhbdu.supabase.co/storage/v1/object/public/partner-images/4fcd9e54-4c77-4a54-88fe-56c8ddc0b495.png", "https://zeiqetimpspjgppfhbdu.supabase.co/storage/v1/object/public/partner-images/6b43509e-3f29-49fc-9ca7-51d7eb537cc4.png"]', '["Wildlife conservation"]', '["birds", "walk"]', 9075, true, 8, true, 'Ol Pejeta Conservancy, Laikipia', now(), now()),

-- Night Game Drive – Ol Pejeta
(gen_random_uuid(), 'ed72b0f5-4fec-48e3-b6fa-977a00420baa', 'Night Game Drive – Ol Pejeta', 'night-game-drive-ol-pejeta', 'Experience the thrill of a night game drive in Ol Pejeta Conservancy. Discover nocturnal wildlife behavior, spot elusive predators, and learn about the unique challenges and opportunities of nighttime conservation work.', '/lovable-uploads/fe11b3d0-bbb8-421a-a54a-c2343a14ec50.png', '["https://zeiqetimpspjgppfhbdu.supabase.co/storage/v1/object/public/partner-images/fe11b3d0-bbb8-421a-a54a-c2343a14ec50.png", "https://zeiqetimpspjgppfhbdu.supabase.co/storage/v1/object/public/partner-images/184835e0-a9f6-4d05-b918-916122306cde.png"]', '["Wildlife conservation"]', '["game drive", "night"]', 9075, true, 6, true, 'Ol Pejeta Conservancy, Laikipia', now(), now()),

-- Northern White Rhinos – Ol Pejeta
(gen_random_uuid(), 'ed72b0f5-4fec-48e3-b6fa-977a00420baa', 'Northern White Rhinos – Ol Pejeta', 'northern-white-rhinos-ol-pejeta', 'Visit the last two northern white rhinos on Earth at Ol Pejeta Conservancy. Learn about groundbreaking conservation science, assisted reproduction efforts, and the race to save this species from extinction through innovative technology.', '/lovable-uploads/ddffabed-5ad6-4675-9022-54618ae8d95c.png', '["https://zeiqetimpspjgppfhbdu.supabase.co/storage/v1/object/public/partner-images/ddffabed-5ad6-4675-9022-54618ae8d95c.png", "https://zeiqetimpspjgppfhbdu.supabase.co/storage/v1/object/public/partner-images/e0c2d6be-e7b9-46ff-8698-69f4c3ac5482.png"]', '["Wildlife conservation"]', '["rhino", "sanctuary"]', 9075, true, 8, true, 'Ol Pejeta Conservancy, Laikipia', now(), now()),

-- Sweetwaters Chimpanzee Conservation Tour
(gen_random_uuid(), 'ed72b0f5-4fec-48e3-b6fa-977a00420baa', 'Sweetwaters Chimpanzee Conservation Tour', 'sweetwaters-chimpanzee-conservation-tour', 'Visit the only chimpanzee sanctuary in Kenya at Sweetwaters in Ol Pejeta Conservancy. Meet rescued chimpanzees, learn about their rehabilitation, and discover the important role of sanctuaries in primate conservation.', '/lovable-uploads/e28a2b5d-1600-4e1d-8326-9d5d2bb9ce2a.png', '["https://zeiqetimpspjgppfhbdu.supabase.co/storage/v1/object/public/partner-images/e28a2b5d-1600-4e1d-8326-9d5d2bb9ce2a.png", "https://zeiqetimpspjgppfhbdu.supabase.co/storage/v1/object/public/partner-images/dab51ea2-808e-4595-b1eb-a8c642771ee8.png"]', '["Wildlife conservation"]', '["chimpanzee", "tour"]', 9075, true, 10, true, 'Sweetwaters, Ol Pejeta Conservancy', now(), now()),

-- Ol Pejeta Lion Tracking Tour
(gen_random_uuid(), 'ed72b0f5-4fec-48e3-b6fa-977a00420baa', 'Ol Pejeta Lion Tracking Tour', 'ol-pejeta-lion-tracking-tour', 'Track lions with expert guides and researchers at Ol Pejeta Conservancy. Learn about lion behavior, conservation challenges, and the latest tracking technology used to protect these apex predators in their natural habitat.', '/lovable-uploads/467b343a-afeb-4589-b353-0cf3d27770a0.png', '["https://zeiqetimpspjgppfhbdu.supabase.co/storage/v1/object/public/partner-images/467b343a-afeb-4589-b353-0cf3d27770a0.png", "https://zeiqetimpspjgppfhbdu.supabase.co/storage/v1/object/public/partner-images/c007cec4-d0cc-4fb1-b485-3eeb6775a94c.png"]', '["Wildlife conservation"]', '["lion", "tracking"]', 9075, true, 6, true, 'Ol Pejeta Conservancy, Laikipia', now(), now()),

-- K9 Handler Day – Ol Pejeta
(gen_random_uuid(), 'ed72b0f5-4fec-48e3-b6fa-977a00420baa', 'K9 Handler Day – Ol Pejeta', 'k9-handler-day-ol-pejeta', 'Spend a day with K9 anti-poaching units at Ol Pejeta Conservancy. Learn about the crucial role of detection dogs in wildlife protection, meet the handlers, and discover how these teams work to combat poaching and wildlife crime.', '/lovable-uploads/ba1c2e8e-98b4-4179-b5ef-87c52a8e2a4b.png', '["https://zeiqetimpspjgppfhbdu.supabase.co/storage/v1/object/public/partner-images/ba1c2e8e-98b4-4179-b5ef-87c52a8e2a4b.png", "https://zeiqetimpspjgppfhbdu.supabase.co/storage/v1/object/public/partner-images/c74fc7f6-c650-4d6c-9b2c-7123506ef925.png"]', '["Wildlife conservation"]', '["k9", "ranger"]', 9075, true, 4, true, 'Ol Pejeta Conservancy, Laikipia', now(), now()),

-- Dive into Coral Conservation (Reefolution)
(gen_random_uuid(), 'ed72b0f5-4fec-48e3-b6fa-977a00420baa', 'Dive into Coral Conservation (Reefolution)', 'dive-into-coral-conservation-reefolution', 'Dive into marine conservation with Reefolution''s coral restoration program. Participate in coral planting, learn about reef ecosystems, and contribute to groundbreaking efforts to restore Kenya''s threatened coral reefs through innovative techniques.', '/lovable-uploads/d4888a5b-c6ad-4983-8c53-e2364f663bd4.png', '["https://zeiqetimpspjgppfhbdu.supabase.co/storage/v1/object/public/partner-images/d4888a5b-c6ad-4983-8c53-e2364f663bd4.png", "https://zeiqetimpspjgppfhbdu.supabase.co/storage/v1/object/public/partner-images/8236db6a-4c2e-4c06-864a-bfcdd270ad52.png"]', '["Conservation education"]', '["coral", "diving"]', 10000, false, 8, true, 'Coastal Kenya', now(), now()),

-- Drone Conservation – Mara Elephant
(gen_random_uuid(), 'ed72b0f5-4fec-48e3-b6fa-977a00420baa', 'Drone Conservation – Mara Elephant', 'drone-conservation-mara-elephant', 'Experience cutting-edge conservation technology with the Mara Elephant Project''s drone program. Learn how aerial surveillance protects elephants, prevents human-wildlife conflict, and supports community-based conservation efforts in the Maasai Mara ecosystem.', '/lovable-uploads/a9fc8078-1eb7-433f-8ea8-cc504ca5b048.png', '["https://zeiqetimpspjgppfhbdu.supabase.co/storage/v1/object/public/partner-images/a9fc8078-1eb7-433f-8ea8-cc504ca5b048.png", "https://zeiqetimpspjgppfhbdu.supabase.co/storage/v1/object/public/partner-images/bd06defe-f511-409f-88b1-decacb2392df.png"]', '["Wildlife conservation"]', '["drone", "elephant"]', 10000, false, 6, true, 'Maasai Mara, Kenya', now(), now()),

-- Elephant Researcher – Mara Elephant Project
(gen_random_uuid(), 'ed72b0f5-4fec-48e3-b6fa-977a00420baa', 'Elephant Researcher – Mara Elephant Project', 'elephant-researcher-with-mara-elephant-project', 'Join researchers from the Mara Elephant Project for a day of elephant research and monitoring. Participate in data collection, learn about elephant behavior and social structures, and contribute to long-term conservation science in the Maasai Mara.', '/lovable-uploads/78e36614-c646-4ca7-ab21-547fa3e9d6e0.png', '["https://zeiqetimpspjgppfhbdu.supabase.co/storage/v1/object/public/partner-images/78e36614-c646-4ca7-ab21-547fa3e9d6e0.png", "https://zeiqetimpspjgppfhbdu.supabase.co/storage/v1/object/public/partner-images/a368337f-e909-4d2e-8491-b3ed256f39df.png"]', '["Wildlife conservation"]', '["research", "elephant"]', 10000, false, 4, true, 'Maasai Mara, Kenya', now(), now()),

-- Sustainable Farm Experience – Karen
(gen_random_uuid(), 'ed72b0f5-4fec-48e3-b6fa-977a00420baa', 'Sustainable Farm Experience – Karen', 'sustainable-farm-experience-karen', 'Explore sustainable farming practices in Karen, Nairobi. Learn about organic agriculture, permaculture techniques, and how local communities are implementing environmentally friendly farming methods to support food security and conservation.', '/lovable-uploads/45948e9d-ba26-45b3-b308-f8a6a38f39d6.png', '["https://zeiqetimpspjgppfhbdu.supabase.co/storage/v1/object/public/partner-images/45948e9d-ba26-45b3-b308-f8a6a38f39d6.png", "https://zeiqetimpspjgppfhbdu.supabase.co/storage/v1/object/public/partner-images/b9079424-d55c-4a37-abc9-8320a15ffcee.png"]', '["Community & cultural exploration"]', '["farm", "sustainability"]', 5000, false, 12, true, 'Karen, Nairobi', now(), now()),

-- Morning Bird Walk – Nature Kenya
(gen_random_uuid(), 'ed72b0f5-4fec-48e3-b6fa-977a00420baa', 'Morning Bird Walk – Nature Kenya', 'morning-bird-walk-nature-kenya', 'Start your day with Nature Kenya''s morning bird walk. Discover the incredible diversity of birds in Nairobi''s urban and peri-urban areas, learn identification techniques, and understand the importance of bird conservation in Kenya.', '/lovable-uploads/6a25f8a9-96fd-4721-afde-ac10a66b7d0e.png', '["https://zeiqetimpspjgppfhbdu.supabase.co/storage/v1/object/public/partner-images/6a25f8a9-96fd-4721-afde-ac10a66b7d0e.png", "https://zeiqetimpspjgppfhbdu.supabase.co/storage/v1/object/public/partner-images/53fee6db-8c18-449f-9b8a-0940ef5dd985.png"]', '["Wildlife conservation"]', '["birds", "walk"]', 300, false, 15, true, 'Nairobi', now(), now()),

-- Citizen Scientist – Nairobi Park
(gen_random_uuid(), 'ed72b0f5-4fec-48e3-b6fa-977a00420baa', 'Citizen Scientist – Nairobi Park', 'citizen-scientist-nairobi-park', 'Become a citizen scientist for a day in Nairobi National Park. Participate in wildlife monitoring, data collection, and research activities that contribute to park management and conservation efforts in Kenya''s only urban national park.', '/lovable-uploads/2e803ede-092c-4c9f-ab95-2dbda73dadbe.png', '["https://zeiqetimpspjgppfhbdu.supabase.co/storage/v1/object/public/partner-images/2e803ede-092c-4c9f-ab95-2dbda73dadbe.png", "https://zeiqetimpspjgppfhbdu.supabase.co/storage/v1/object/public/partner-images/12f78b3b-4c70-4ca5-baab-42b4cc16aac3.png"]', '["Conservation education"]', '["citizen science"]', 1500, false, 12, true, 'Nairobi National Park', now(), now()),

-- Karura Forest Specialized Eco Tours
(gen_random_uuid(), 'ed72b0f5-4fec-48e3-b6fa-977a00420baa', 'Karura Forest Specialized Eco Tours', 'karura-forest-specialized-eco-tours', 'Explore Karura Forest on specialized eco-tours with Friends of Karura. Discover indigenous trees, learn about forest restoration efforts, and understand the vital role of urban forests in environmental conservation and community wellbeing.', '/lovable-uploads/7e07f04b-82b6-432c-9064-326ef04a1844.png', '["https://zeiqetimpspjgppfhbdu.supabase.co/storage/v1/object/public/partner-images/7e07f04b-82b6-432c-9064-326ef04a1844.png", "https://zeiqetimpspjgppfhbdu.supabase.co/storage/v1/object/public/partner-images/5247eabe-c5d5-44a7-ae67-cfa37f3aa62f.png"]', '["Conservation education"]', '["forest", "eco-tour"]', 1000, false, 15, true, 'Karura Forest, Nairobi', now(), now()),

-- Opportunity Factory – Eco Innovation Tour
(gen_random_uuid(), 'ed72b0f5-4fec-48e3-b6fa-977a00420baa', 'Opportunity Factory – Eco Innovation Tour', 'opportunity-factory-eco-innovation-tour', 'Discover eco-innovation at the Opportunity Factory. Learn about sustainable technology solutions, participate in innovation workshops, and see how local entrepreneurs are developing environmentally friendly products and services.', '/lovable-uploads/e3017527-f111-4ba7-b356-1c8119ddb3ee.png', '["https://zeiqetimpspjgppfhbdu.supabase.co/storage/v1/object/public/partner-images/e3017527-f111-4ba7-b356-1c8119ddb3ee.png", "https://zeiqetimpspjgppfhbdu.supabase.co/storage/v1/object/public/partner-images/782df8a2-d1fb-4943-abc8-b1327cd041b7.png"]', '["Community & cultural exploration"]', '["innovation", "workshop"]', 2000, false, 20, true, 'Nairobi', now(), now());