-- Add experiences linked to the seeded partners
INSERT INTO experiences (id, partner_id, title, slug, description, hero_image, gallery, themes, activities, price_kes_adult, child_half_price_rule, capacity, visible_on_marketplace, location_text, created_at, updated_at) 
SELECT 
  gen_random_uuid(), 
  p.id,
  e.title,
  e.slug,
  e.description,
  e.hero_image,
  e.gallery::jsonb,
  e.themes::jsonb,
  e.activities::jsonb,
  e.price_kes_adult,
  e.child_half_price_rule,
  15, -- default capacity
  true, -- visible on marketplace
  e.location_text,
  now(),
  now()
FROM partner_profiles p
JOIN (VALUES 
  ('koija-community', 'Koija Cultural Village', 'koija-cultural-village', 'Immerse yourself in the rich cultural heritage of the Samburu people at Koija Cultural Village. Experience traditional dances, learn about ancient customs, and witness the daily life of this proud community.', '/lovable-uploads/08763604-1a22-4da5-a8a1-4daf65cb4b32.png', '["​/lovable-uploads/08763604-1a22-4da5-a8a1-4daf65cb4b32.png"]', '["Community & cultural exploration"]', '["village", "culture", "community"]', 2000, false, 'Samburu County, Kenya'),
  ('sera-conservancy', 'Sera On-Foot Rhino Tracking', 'sera-on-foot-rhino-tracking', 'Experience the thrill of tracking endangered black rhinos on foot in the Sera Conservancy. This unique conservation experience offers intimate wildlife encounters while supporting critical anti-poaching efforts.', '/lovable-uploads/73526904-0f02-4d36-9590-456e0dd5628a.png', '["​/lovable-uploads/73526904-0f02-4d36-9590-456e0dd5628a.png"]', '["Wildlife conservation"]', '["rhino", "tracking", "walking"]', 4000, false, 'Sera Conservancy, Samburu'),
  ('ruko-community-conservancy', 'Giraffe at Ruko Sanctuary', 'giraffe-at-ruko-sanctuary', 'Get up close with endangered Rothschilds giraffes at Ruko Community Conservancy. Learn about giraffe conservation efforts, feeding behaviors, and the communitys role in protecting these magnificent creatures.', '/lovable-uploads/21799448-fabe-49a5-b8b2-3fd811cc804c.png', '["​/lovable-uploads/21799448-fabe-49a5-b8b2-3fd811cc804c.png"]', '["Wildlife conservation"]', '["giraffe", "sanctuary"]', 2000, false, 'Ruko Conservancy, Samburu'),
  ('colobus-conservation', 'Colobus Conservation Guided Eco Tours', 'colobus-conservation-guided-eco-tours', 'Discover the fascinating world of Colobus monkeys and other primates along Kenyas coast. This guided eco-tour showcases conservation efforts to protect endangered primates while supporting local communities.', '/lovable-uploads/1cbd1d3d-c30b-45be-a09e-8c9cc6f1f87b.png', '["​/lovable-uploads/1cbd1d3d-c30b-45be-a09e-8c9cc6f1f87b.png"]', '["Wildlife conservation"]', '["primates", "eco-tour"]', 1500, false, 'Coastal Kenya'),
  ('local-ocean-watamu', 'Ocean Conservation Day – Watamu', 'ocean-conservation-day-watamu', 'Join a hands-on ocean conservation workshop in Watamu. Learn about marine ecosystems, participate in beach cleanups, and discover how local communities are protecting coral reefs and marine life.', '/lovable-uploads/a6c0b2b9-fd77-4472-a600-d2f163add078.png', '["​/lovable-uploads/a6c0b2b9-fd77-4472-a600-d2f163add078.png"]', '["Conservation education"]', '["ocean", "workshop"]', 1000, false, 'Watamu, Coastal Kenya'),
  ('kenya-forest-heritage', 'Tree Walk – Kenya Forest Heritage', 'tree-walk-kenya-forest-heritage', 'Explore Kenyas indigenous forest heritage through guided tree walks. Learn about native species, traditional uses of forest resources, and ongoing conservation efforts to preserve these vital ecosystems.', '/lovable-uploads/f0dcab56-c695-41ac-bf57-3a9e350158f0.png', '["​/lovable-uploads/f0dcab56-c695-41ac-bf57-3a9e350158f0.png"]', '["Conservation education"]', '["forest", "walk", "trees"]', 500, false, 'Nairobi and surroundings'),
  ('nature-kenya', 'Dudu Walk – Insect Exploration', 'dudu-walk-insect-exploration', 'Discover the incredible world of insects and their vital role in ecosystems. This educational walk with Nature Kenya experts reveals the fascinating diversity of Kenyas invertebrate life.', '/lovable-uploads/89f29078-42d9-498b-91e8-de9387a64250.png', '["​/lovable-uploads/89f29078-42d9-498b-91e8-de9387a64250.png"]', '["Conservation education"]', '["insects", "education", "walk"]', 300, true, 'Nairobi, Kenya'),
  ('giraffe-centre-afew', 'Giraffe Centre Visit', 'giraffe-centre-visit', 'Meet the famous Rothschilds giraffes at the Giraffe Centre in Nairobi. Feed these gentle giants and learn about AFEW⁄s conservation efforts to protect endangered giraffe species.', '/lovable-uploads/f39fee39-a385-4e10-a818-084c4d1811fd.png', '["​/lovable-uploads/f39fee39-a385-4e10-a818-084c4d1811fd.png"]', '["Wildlife conservation"]', '["giraffe", "feeding", "education"]', 1000, true, 'Nairobi, Kenya'),
  ('reteti-elephant-sanctuary', 'Reteti Elephant Orphanage Visit', 'reteti-elephant-orphanage-visit', 'Visit the community-owned Reteti Elephant Sanctuary and witness the incredible work being done to rescue and rehabilitate orphaned elephants back to the wild.', '/lovable-uploads/d42dcb33-a2f6-4418-8d2a-921127f8d45a.png', '["​/lovable-uploads/d42dcb33-a2f6-4418-8d2a-921127f8d45a.png"]', '["Wildlife conservation"]', '["elephants", "sanctuary", "orphanage"]', 3000, false, 'Samburu County, Kenya'),
  ('ol-pejeta-conservancy', 'Ol Pejeta Night Game Drive', 'ol-pejeta-night-game-drive', 'Experience the magic of the African night with a guided game drive through Ol Pejeta Conservancy. Spot nocturnal wildlife and learn about nighttime conservation activities.', '/lovable-uploads/dc2fa3f6-3095-4f03-9f50-d78d7cceba81.png', '["​/lovable-uploads/dc2fa3f6-3095-4f03-9f50-d78d7cceba81.png"]', '["Wildlife conservation"]', '["night drive", "nocturnal", "wildlife"]', 3500, false, 'Laikipia County, Kenya'),
  ('ol-pejeta-conservancy', 'Northern White Rhinos Experience', 'northern-white-rhinos-experience', 'Meet Sudans legacy - the last northern white rhinos on Earth. Learn about cutting-edge conservation science and the race to save this subspecies from extinction.', '/lovable-uploads/dc2fa3f6-3095-4f03-9f50-d78d7cceba81.png', '["​/lovable-uploads/dc2fa3f6-3095-4f03-9f50-d78d7cceba81.png"]', '["Wildlife conservation"]', '["rhino", "conservation science", "endangered species"]', 5000, false, 'Laikipia County, Kenya'),
  ('ol-pejeta-conservancy', 'Sweetwaters Chimpanzee Sanctuary', 'sweetwaters-chimpanzee-sanctuary', 'Visit the only chimpanzee sanctuary in Kenya at Ol Pejeta. Meet rescued chimpanzees and learn about primate conservation and rehabilitation efforts.', '/lovable-uploads/dc2fa3f6-3095-4f03-9f50-d78d7cceba81.png', '["​/lovable-uploads/dc2fa3f6-3095-4f03-9f50-d78d7cceba81.png"]', '["Wildlife conservation"]', '["chimpanzees", "sanctuary", "primates"]', 2500, false, 'Laikipia County, Kenya'),
  ('ol-pejeta-conservancy', 'Lion Tracking Experience', 'lion-tracking-experience', 'Join researchers in tracking and monitoring lions in the Ol Pejeta ecosystem. Learn about lion behavior, conservation challenges, and community coexistence programs.', '/lovable-uploads/dc2fa3f6-3095-4f03-9f50-d78d7cceba81.png', '["​/lovable-uploads/dc2fa3f6-3095-4f03-9f50-d78d7cceba81.png"]', '["Wildlife conservation"]', '["lions", "tracking", "research"]', 4000, false, 'Laikipia County, Kenya'),
  ('ol-pejeta-conservancy', 'K9 Anti-Poaching Unit Training', 'k9-anti-poaching-unit-training', 'Experience anti-poaching efforts firsthand by joining K9 handler training sessions. Learn about conservation security and the vital role of detection dogs in wildlife protection.', '/lovable-uploads/dc2fa3f6-3095-4f03-9f50-d78d7cceba81.png', '["​/lovable-uploads/dc2fa3f6-3095-4f03-9f50-d78d7cceba81.png"]', '["Wildlife conservation"]', '["anti-poaching", "k9", "security training"]', 3000, false, 'Laikipia County, Kenya'),
  ('reefolution', 'Coral Restoration Workshop', 'coral-restoration-workshop', 'Learn cutting-edge coral restoration techniques with Reefolution. Participate in coral fragment collection, nursery maintenance, and reef transplantation activities.', '/lovable-uploads/d4888a5b-c6ad-4983-8c53-e2364f663bd4.png', '["​/lovable-uploads/d4888a5b-c6ad-4983-8c53-e2364f663bd4.png"]', '["Conservation education"]', '["coral", "restoration", "marine"]', 2500, false, 'Coastal Kenya'),
  ('reefolution', 'Marine Protected Area Snorkeling', 'marine-protected-area-snorkeling', 'Explore healthy coral reefs in marine protected areas managed by Reefolution. Witness successful coral restoration efforts and vibrant marine biodiversity.', '/lovable-uploads/d4888a5b-c6ad-4983-8c53-e2364f663bd4.png', '["​/lovable-uploads/d4888a5b-c6ad-4983-8c53-e2364f663bd4.png"]', '["Wildlife conservation"]', '["snorkeling", "coral reefs", "marine conservation"]', 1800, false, 'Coastal Kenya'),
  ('mara-elephant-project', 'Elephant Tracking with Drones', 'elephant-tracking-with-drones', 'Join cutting-edge elephant research using drone technology. Learn how aerial monitoring helps protect elephant populations and mitigate human-wildlife conflict in the Mara ecosystem.', '/lovable-uploads/a9fc8078-1eb7-433f-8ea8-cc504ca5b048.png', '["​/lovable-uploads/a9fc8078-1eb7-433f-8ea8-cc504ca5b048.png"]', '["Wildlife conservation"]', '["elephants", "drones", "research"]', 4500, false, 'Maasai Mara, Kenya'),
  ('ewaso-lions', 'Ewaso Lion Tracking', 'ewaso-lion-tracking', 'Track and monitor lions in the Ewaso ecosystem with community conservationists. Learn about lion behavior, territory mapping, and community-based conservation approaches.', '/public/logos/olp.png', '["/public/logos/olp.png"]', '["Wildlife conservation"]', '["lions", "tracking", "community conservation"]', 3800, false, 'Samburu County, Kenya'),
  ('ewaso-lions', 'Lion Guardian Community Program', 'lion-guardian-community-program', 'Join the innovative Lion Guardian program that transforms traditional warriors into lion protectors. Learn about human-wildlife coexistence in Maasai communities.', '/public/logos/olp.png', '["/public/logos/olp.png"]', '["Community & cultural exploration"]', '["community", "lion protection", "maasai culture"]', 3200, false, 'Maasai Mara, Kenya'),
  ('kenya-wildlife-service', 'KWS Ranger Training Experience', 'kws-ranger-training-experience', 'Experience a day in the life of a Kenya Wildlife Service ranger. Learn about wildlife management, anti-poaching operations, and community engagement in conservation.', '/public/logos/reef.png', '["/public/logos/reef.png"]', '["Conservation education"]', '["ranger training", "wildlife management", "conservation"]', 2000, false, 'Nairobi, Kenya'),
  ('sheldrick-wildlife-trust', 'Sheldrick Elephant Adoption Program', 'sheldrick-elephant-adoption-program', 'Visit the Sheldrick Wildlife Trust and learn about their pioneering elephant orphan rescue and rehabilitation program. Meet the keepers and adopted elephants.', '/public/logos/mep.png', '["/public/logos/mep.png"]', '["Wildlife conservation"]', '["elephants", "adoption", "rehabilitation"]', 2800, false, 'Nairobi, Kenya'),
  ('david-sheldrick-wildlife-trust', 'David Sheldrick Orphanage Tour', 'david-sheldrick-orphanage-tour', 'Visit the famous David Sheldrick Wildlife Trust elephant orphanage. Watch the 11am feeding session and learn about elephant rescue, rehabilitation and reintegration.', '/public/logos/afeW.png', '["/public/logos/afeW.png"]', '["Wildlife conservation"]', '["elephants", "orphanage", "feeding"]', 1500, true, 'Nairobi, Kenya')
) e(partner_slug, title, slug, description, hero_image, gallery, themes, activities, price_kes_adult, child_half_price_rule, location_text) ON p.slug = e.partner_slug
WHERE p.kyc_status = 'approved'
ON CONFLICT (slug) DO NOTHING;